spring.application.name=ieojuda

# .env 파일 import
spring.config.import=optional:file:.env[.properties]

# JPA + Hibernate Setting
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Postgresql DB 연결
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#openAI
openai.api-key=${OPENAI_API_KEY}
openai.api-url=https://api.openai.com/v1/chat/completions
openai.model=gpt-3.5-turbo
#Gmail 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
